services:
  alyo-app:
    # Membangun image dari Dockerfile di direktori saat ini
    build:
      context: .
      dockerfile: Dockerfile
    # Menamakan container agar mudah diidentifikasi
    container_name: alyo_api
    # Menggunakan file .env untuk variabel lingkungan
    env_file:
      - .env
    ports:
      # Memetakan port dari host ke container.
      # ${PORT:-8080} berarti: gunakan variabel PORT dari .env,
      # jika tidak ada, gunakan 8080 sebagai default.
      - "${PORT:-8080}:${PORT:-8080}"
    # Restart container secara otomatis jika terjadi kegagalan
    restart: unless-stopped
    # Menetapkan network (opsional tapi praktik yang baik)
    depends_on:
      - pgbouncer
    networks:
      - alyo-net
    command: sh -c "/app/bin/worker & /app/bin/webapp"

  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p1
    container_name: alyo_pgbouncer
    # Mount file konfigurasi yang kita buat ke dalam container
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    restart: unless-stopped
    networks:
      - alyo-net

networks:
  alyo-net:
    driver: bridge
    external: true
